spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver
    
mybatis:
  type-aliases-package: com.james.pojo